version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly


gAAAAABpyGDp1gHZ7pZ0RiBFulBrbMbWv9TjCFDNsYxT_RfrMPtJUB62s2I3idhtrWh4WCPY1DNlfsxAKq8CVbLrvAl2_u19eA==